const { test } = require('node:test');
const assert = require('node:assert/strict');
const vm = require('node:vm');
const fs = require('node:fs');
const path = require('node:path');
const { EventEmitter } = require('node:events');
const source = fs.readFileSync(path.join(__dirname, '../renderer/peer.js'), 'utf8');
function setup() {
  let counter = 0; const timers = new Map();
  class Conn extends EventEmitter { constructor(peer) { super(); this.peer = peer; this.serialization = 'binary'; this.metadata = { protocol: 2 }; this.open = true; this.sent = []; } send(data) { this.sent.push(data); } close() { this.open = false; this.emit('close'); } }
  class Peer extends EventEmitter { constructor(id) { super(); this.id = id || 'guest-id'; this.open = true; } connect(id, options) { this.lastConnectOptions = options; return new Conn(id); } destroy() { this.destroyed = true; } reconnect() { this.disconnected = false; } }
  const sandbox = { window: {}, EventTarget, CustomEvent, Peer, crypto, performance, Date, TextEncoder, setTimeout: (fn,ms) => { timers.set(++counter,{fn,ms}); return counter; }, clearTimeout: id => timers.delete(id), setInterval: (fn,ms) => { timers.set(++counter,{fn,ms}); return counter; }, clearInterval: id => timers.delete(id) };
  vm.runInNewContext(source, sandbox);
  const api = sandbox.window.Glup;
  function host() { const room = new api.Room(); room.start('host'); room.peer.emit('open', room.peer.id); return room; }
  function join(room,id) { const conn = new Conn(id); room.peer.emit('connection',conn); conn.emit('open'); conn.emit('data',{type:'hello',protocol:2,profile:{name:id}}); return conn; }
  return {...api, timers, Conn, host, join};
}

test('ID e convite validados; URLs externas recusadas', () => { const {parseRoom} = setup(); assert.equal(parseRoom('glupstreamxd://glup-a8f3k2/'),'glup-a8f3k2'); for(const v of ['https://evil/glup-a8f3k2','glup-x','glup-a8f3k2?x=1']) assert.equal(parseRoom(v),null); });
test('10 espectadores entram; o 11º é recusado sem afetar a sala', () => { const {host,join} = setup(); const room=host(); for(let i=0;i<10;i++)join(room,'peer'+i); assert.equal(room.members.size,11); assert.equal(room.viewerCount,10); const extra=join(room,'extra'); assert.equal(extra.sent[0].type,'rejected'); assert.equal(room.viewerCount,10); room.leave(); });
test('host encaminha a todos e impede falsificação da identidade', () => { const {host,join} = setup(); const room=host(), a=join(room,'a'), b=join(room,'b'); a.emit('data',{type:'chat',text:'oi',sender:room.peer.id}); const received=b.sent.find(x=>x.type==='chat'); assert.equal(received.sender,'a'); assert.equal(received.text,'oi'); room.leave(); });
test('espectador sai e reconecta sem desconectar os demais', () => { const {host,join} = setup(); const room=host(), a=join(room,'a'), b=join(room,'b'); a.close(); assert.equal(room.viewerCount,1); assert.equal(room.state,'connected'); assert.equal(b.open,true); join(room,'a'); assert.equal(room.viewerCount,2); room.leave(); });
test('figurinhas e fotos recusam SVG, URL externa e tamanho excessivo', () => { const {imageOK,cleanProfile} = setup(); assert.equal(imageOK('https://a/image.png'),false); assert.equal(imageOK('data:image/svg+xml;base64,AAAA'),false); assert.equal(imageOK('data:image/png;base64,'+'A'.repeat(60000)),false); assert.equal(cleanProfile({name:'x',photo:'data:image/png;base64,'+'A'.repeat(6000)}).photo,''); });
test('protocolo antigo não ocupa uma vaga', () => { const {host,Conn} = setup(); const room=host(); const conn=new Conn('old'); conn.metadata={}; room.peer.emit('connection',conn);conn.emit('open');assert.match(conn.sent[0].message,/2.0/);assert.equal(room.links.size,0);room.leave(); });
test('callbacks antigos não afetam a nova sala', () => { const {Room}=setup();const room=new Room();room.start('host');const old=room.peer;room.start('host');old.emit('open','old');old.emit('error',{type:'network'});assert.equal(room.state,'connecting');room.leave(); });
test('recuperação do convidado encerra após 10 segundos', () => { const {Room,timers}=setup();const room=new Room();let error;room.addEventListener('error',e=>error=e.detail);room.start('guest','glup-a8f3k2');room.recover();[...timers.values()].find(t=>t.ms===10000).fn();assert.equal(room.state,'offline');assert.match(error,/10 segundos/);assert.equal(timers.size,0); });
test('Pix fornecido tem CRC íntegro e foi preservado', () => { const code=fs.readFileSync(path.join(__dirname,'../renderer/extras.js'),'utf8');const pix=/const PIX = '([^']+)'/.exec(code)[1];let crc=65535;for(const ch of pix.slice(0,-4)){crc^=ch.charCodeAt(0)<<8;for(let i=0;i<8;i++)crc=(crc&32768)?((crc<<1)^0x1021)&65535:(crc<<1)&65535;}assert.equal(crc.toString(16).toUpperCase(),pix.slice(-4)); });
test('reconexão do broker pode acontecer mais de uma vez',()=>{const {host}=setup();const room=host();room.peer.disconnected=true;room.peer.emit('disconnected');assert.ok(room.brokerRetry);room.peer.emit('open',room.peer.id);assert.equal(room.brokerRetry,null);room.peer.disconnected=true;room.peer.emit('disconnected');assert.ok(room.brokerRetry);room.leave();});
test('convidado negocia BinaryPack com fragmentação automática',()=>{const {Room}=setup();const room=new Room();room.start('guest','glup-a8f3k2');room.peer.emit('open','guest-id');assert.equal(room.peer.lastConnectOptions.serialization,'binary');room.leave();});
test('erro de tamanho da mensagem não derruba participantes',()=>{const {host,join}=setup();const room=host(),a=join(room,'a'),b=join(room,'b');a.emit('error',{type:'message-too-big'});assert.equal(room.viewerCount,2);assert.equal(a.open,true);assert.equal(b.open,true);assert.equal(room.state,'connected');room.leave();});
test('cliente antigo JSON recebe instrução de atualização sem entrar na sala',()=>{const {host,Conn}=setup();const room=host(),conn=new Conn('legacy');conn.serialization='json';room.peer.emit('connection',conn);conn.emit('open');assert.equal(conn.sent[0].type,'rejected');assert.match(conn.sent[0].message,/2.0.1/);assert.equal(room.links.size,0);room.leave();});
test('envio legado é validado em bytes UTF-8 antes de chamar PeerJS',()=>{const {host,Conn}=setup();const room=host(),conn=new Conn('legacy');conn.serialization='json';const packet={type:'chat',text:'漢'.repeat(6000)};assert.ok(JSON.stringify(packet).length<16300);assert.equal(room.rawSend(conn,packet),false);assert.equal(conn.sent.length,0);assert.equal(conn.open,true);room.leave();});
test('figura acima de 16 KB e dentro de 50 KB é encaminhada intacta a todos',()=>{const {host,join}=setup();const room=host(),a=join(room,'a'),b=join(room,'b');const image='data:image/webp;base64,'+'A'.repeat(30000);assert.equal(room.send({type:'sticker',image}),true);assert.equal(a.sent.find(p=>p.type==='sticker').image,image);assert.equal(b.sent.find(p=>p.type==='sticker').image,image);assert.equal(room.viewerCount,2);room.leave();});
test('saturação de envio informa falha sem fechar conexões',()=>{const {host,join}=setup();const room=host(),a=join(room,'a'),b=join(room,'b');a.dataChannel={bufferedAmount:600000};assert.equal(room.send({type:'sticker',sticker:'wave'}),false);assert.equal(a.open,true);assert.equal(b.open,true);assert.equal(room.viewerCount,2);room.leave();});
